import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import React from "react";
import { WindowsTitleBar } from "./components/WindowsTitleBar";
import { Appbar } from "./components/Appbar";
import { BottomNav } from "./components/BottomNav";
import { MainLayout } from "./components/MainLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: 'swap',
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "EchoDeck",
  description: "Generated by Aakash A. Joshi",
  icons: {
    icon: "/favicon.png",
    apple: "/icons/apple-touch-icon.png",
  },
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    title: "EchoDeck",
    statusBarStyle: "black-translucent",
  },
};

export const viewport: Viewport = {
  themeColor: "#2563eb",
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <WindowsTitleBar />
          <div className="fixed top-0 left-0 right-0 z-50">
            <Appbar />
          </div>
          <MainLayout>
            {children}
          </MainLayout>
          <BottomNav />
        </Providers>
      </body>
    </html>
  );
}
